name: Jekyll Deploy

on:
  push:
    branches:
      - main

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1
      - name: validate-bio-json-file
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\bio.json$"
      - name: Build & Deploy to GitHub Pages
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - uses: joshlarsen/jekyll4-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
